# Python "científico": módulo `numpy`

![](images_scipython/sci_python.png)

## `numpy`

### Operações "vectoriais"

In [1]:
import numpy as np

In [2]:
numbers = [0.0, 0.2, 0.5, 1.0, 1.1]
x = np.array(numbers)

print 'x = {}\n'.format(x)

y = 4 * x

print 'y = {}\n'.format(y)

x = [ 0.   0.2  0.5  1.   1.1]

y = [ 0.   0.8  2.   4.   4.4]



A função `np.array()` transformou a lista num objeto do tipo _array_.

Estes objetos suportam operações aritméticas "vetoriais": na expressão `y = 4 * x` a multiplicação por 4 é aplicada a todos os elementos de `x`. O resultado é também um _array_.

### Criação de _arrays_ com as funções `.array()`, `.arange()` e `.linspace()`

In [3]:
x = np.array([1, 1.2, 3, 3.5])
print 'Criado com .array(), x = {}\n'.format(x)

x = np.arange(1.5, 2.5, 0.1)
print 'Criado com .arange(), x = {}\n'.format(x)

x = np.linspace(1, 2, 5)
print 'Criado com .linspace(), x = {}\n'.format(x)

Criado com .array(), x = [ 1.   1.2  3.   3.5]

Criado com .arange(), x = [ 1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4]

Criado com .linspace(), x = [ 1.    1.25  1.5   1.75  2.  ]



In [4]:
x = np.linspace (0.0, 2.5, 20)
print 'x'
print x

y = 4 * x**2 -3

print 
print 'y'
print y

x
[ 0.          0.13157895  0.26315789  0.39473684  0.52631579  0.65789474
  0.78947368  0.92105263  1.05263158  1.18421053  1.31578947  1.44736842
  1.57894737  1.71052632  1.84210526  1.97368421  2.10526316  2.23684211
  2.36842105  2.5       ]

y
[ -3.          -2.93074792  -2.72299169  -2.3767313   -1.89196676
  -1.26869806  -0.50692521   0.3933518    1.43213296   2.60941828
   3.92520776   5.37950139   6.97229917   8.70360111  10.5734072
  12.58171745  14.72853186  17.01385042  19.43767313  22.        ]


### Dimensões (`shape`)

In [5]:
x = np.linspace(1,20,20)
print 'x = {}\n'.format(x)

x.shape = (5,4)
# significa 5 linhas e 4 colunas

print 'Após mudar a "shape"\nx =\n{}'.format(x)

x = [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.  19.  20.]

Após mudar a "shape"
x =
[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [ 13.  14.  15.  16.]
 [ 17.  18.  19.  20.]]


### Criação de _arrays_ com `.array()`, `.ones()`, `.zeros()`, `.eye()`, `.diag()`

In [6]:
x = np.array( [[1, 1.2, 3], [1.3,5.1,1.3]] )
print 'np.array( [[1, 1.2, 3], [1.3,5.1,1.3]] ) =\n{}\n'.format(x)

x = np.ones((3,2))
print 'np.ones((3,2)) =\n{}\n'.format(x)

x = np.zeros((3,2))
print 'np.zeros((3,2)) =\n{}\n'.format(x)

x = np.eye(3)
print 'np.eye(3) =\n{}\n'.format(x)

x = np.diag([1.2, 3.2, 4.1, 6.3])
print 'np.diag([1.2, 3.2, 4.1, 6.3]) =\n{}'.format(x)

np.array( [[1, 1.2, 3], [1.3,5.1,1.3]] ) =
[[ 1.   1.2  3. ]
 [ 1.3  5.1  1.3]]

np.ones((3,2)) =
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]

np.zeros((3,2)) =
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]

np.eye(3) =
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

np.diag([1.2, 3.2, 4.1, 6.3]) =
[[ 1.2  0.   0.   0. ]
 [ 0.   3.2  0.   0. ]
 [ 0.   0.   4.1  0. ]
 [ 0.   0.   0.   6.3]]


### Indexação a várias dimensões

In [7]:
x = np.linspace(1,20,20).reshape((5,4))
print 'x =\n{}\n'.format(x)
print 'x[3,1] =\n{}\n'.format(x[3,1])
print 'x[3, :] =\n{}\n'.format(x[3, :])
print 'x[0:2, 0:2] =\n{}\n'.format(x[0:2, 0:2])

x =
[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [ 13.  14.  15.  16.]
 [ 17.  18.  19.  20.]]

x[3,1] =
14.0

x[3, :] =
[ 13.  14.  15.  16.]

x[0:2, 0:2] =
[[ 1.  2.]
 [ 5.  6.]]



### Indexação booleana

In [8]:
x = np.linspace(1,20,20)
print 'x = {}\n'.format(x)

print 'x > 7\n {}\n'.format(x > 7)

print 'x[x > 7] \n {}\n'.format(x[x > 7])
print 

x = [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.  19.  20.]

x > 7
 [False False False False False False False  True  True  True  True  True
  True  True  True  True  True  True  True  True]

x[x > 7] 
 [  8.   9.  10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]




### Indexação com listas de inteiros ou _arrays_

In [9]:
x = np.linspace(5,15,11)
print 'x = {}\n'.format(x)

i = [1,4,5,6,8]
print 'i = {}\n'.format(i)

print 'x[i] =\n{}\n'.format(x[i])

x = [  5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.]

i = [1, 4, 5, 6, 8]

x[i] =
[  6.   9.  10.  11.  13.]



### Exemplos de algumas funções do `numpy`.

In [10]:
x = np.roots ([1.0,2.0,1.0,1.0])
print
print 'raízes de x**3 + 2 x**2 + x + 1'
print x


raízes de x**3 + 2 x**2 + x + 1
[-1.75487767+0.j         -0.12256117+0.74486177j -0.12256117-0.74486177j]


### Geração de números aleatórios.

Obter valores aleatórios das seguintes distribuições:

**Poisson** (usada para número de ocorrências durante um intervalo)

$p(x, \lambda) = \frac{e^{-x} \lambda^x}{x!}$ com $x = 0, 1, 2, ...$

**Normal (0,1)**

$f(x) = \frac{1}{\sqrt{2\pi}} e^{-x^2 / 2}$ com $x \in [-\infty, \infty]$

In [11]:
print '20 valores aleatórios da distribuição de Poisson com lambda = 3'
print np.random.poisson(3, 20)

print '\n5 valores aleatórios da distribuição N(0,1)'
print np.random.randn(5)

20 valores aleatórios da distribuição de Poisson com lambda = 3
[7 1 3 4 1 3 2 1 7 0 6 4 2 2 1 5 3 1 3 3]

5 valores aleatórios da distribuição N(0,1)
[-1.58803295  0.97400792  1.88910888 -1.28964779 -0.60016376]


**Problema**: "Provar" que a média e a variância da distribuição de Poisson são ambas iguais a $ \lambda $.

In [12]:
sample = np.random.poisson(3, 100000)

print 'Média = ', np.mean(sample)

print 'Variância =', np.var(sample)

Média =  3.01252
Variância = 3.0000032496


### Exemplos de operações vectoriais

In [13]:
#somar os primeiros 20 quadrados perfeitos
print sum(np.arange(20)**2)

2470


In [14]:
#mostrar que as diferenças entre os quadrados perfeitos sucessivos são os numeros ímpares
quads = np.arange(20)**2
difs = quads[1:] - quads[0:-1]
print difs

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [15]:
## #somar as raízes quadradas que são numeros inteiros at 100
roots = np.arange(0,101)**0.5
print sum(roots[np.trunc(roots) == roots])

55.0


In [16]:
# mostrar que a série alternada dos inversos converge para log 2
i = np.arange(1,1000000)
difs =  np.abs(np.add.accumulate((-1)**(i+1) * 1.0/i) - np.log(2))
print difs[-20:]

[  5.00009693e-07   5.00009307e-07   5.00008693e-07   5.00008307e-07
   5.00007693e-07   5.00007307e-07   5.00006693e-07   5.00006307e-07
   5.00005693e-07   5.00005307e-07   5.00004693e-07   5.00004307e-07
   5.00003693e-07   5.00003307e-07   5.00002693e-07   5.00002307e-07
   5.00001693e-07   5.00001307e-07   5.00000693e-07   5.00000307e-07]


### Matrizes e álgebra linear

In [17]:
A = np.matrix ([[1, 2, 3], [2, 1, 6], [1, 7, 4]])

print 'A\n{}\n'.format(A)

B = np.matrix ([1,2,3])
print 'B\n{}\n'.format(B)

BT = B.T 
print 'B.T\n{}\n'.format(BT)

C = A * B.T
print 'C = A * B.T\n{}\n'.format(C)

A
[[1 2 3]
 [2 1 6]
 [1 7 4]]

B
[[1 2 3]]

B.T
[[1]
 [2]
 [3]]

C = A * B.T
[[14]
 [22]
 [27]]



In [18]:
A = np.matrix ([[1.0, 2, 3], [2, 1, 6], [1, 7, 4]])
print 'A\n{}\n'.format(A)

B = np.matrix ([1,2,3]).T
print 'B\n{}\n'.format(B)

X = np.linalg.solve(A, B)
print 'X (solução de A*X = B)\n{}'.format(X)

A
[[ 1.  2.  3.]
 [ 2.  1.  6.]
 [ 1.  7.  4.]]

B
[[1]
 [2]
 [3]]

X (solução de A*X = B)
[[-5.]
 [ 0.]
 [ 2.]]


In [19]:
A = np.matrix ([[1.0, 2, 3], [2, 1, 6], [1, 7, 4]])
print 'A\n{}\n'.format(A)

AINV = np.linalg.inv(A)
print 'Inversa de A\n{}\n'.format(AINV)

X = A * AINV
print 'A * A**-1'
print '{}'.format(X)

A
[[ 1.  2.  3.]
 [ 2.  1.  6.]
 [ 1.  7.  4.]]

Inversa de A
[[ 12.66666667  -4.33333333  -3.        ]
 [  0.66666667  -0.33333333   0.        ]
 [ -4.33333333   1.66666667   1.        ]]

A * A**-1
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## `sympy`

### Símbolos e álgebra básica

In [20]:
from sympy import Symbol

x = Symbol('x')
y = Symbol('y')

expr = 2**x + x**2 -3

print expr
print
print x+y+x-y

2**x + x**2 - 3

2*x


In [21]:
a = (x+y)**2
print a
print a.expand()
print
print a.subs(x, 1).expand()
print a.subs(x, 1).expand().subs(y, 1)

(x + y)**2
x**2 + 2*x*y + y**2

y**2 + 2*y + 1
4


### Limites

In [22]:
from sympy import Symbol, limit, diff, integrate, sin, oo

x = Symbol('x')
y = Symbol('y')

expr = 2**x + x**2 -3

print expr

print limit(sin(x)/x, x, 0)
print limit(x, x, oo)
print limit(1/x, x, oo)

2**x + x**2 - 3
1
oo
0


### Derivadas e integrais

In [23]:
print diff(sin(x), x)
print diff(sin(2*x), x)
print diff(expr, x)
print diff(expr, x, 3)
print '-------------------------------'
print integrate(sin(x), x)

cos(x)
2*cos(2*x)
2**x*log(2) + 2*x
2**x*log(2)**3
-------------------------------
-cos(x)


In [24]:
from sympy import Symbol, Matrix, pprint

x = Symbol('x')
y = Symbol('y')

M = Matrix([[1,x], [y,1]])
print 'M'
print M
print
print 'M'
pprint(M)
print '\n------------------------'

MINV = M.inv()
print 'MINV'
print MINV
print
print 'MINV'
pprint(MINV)

print '\n------------------------'
d = M.det()
print 'M.det =', d

M
Matrix([[1, x], [y, 1]])

M
⎡1  x⎤
⎢    ⎥
⎣y  1⎦

------------------------
MINV
Matrix([[x*y/(-x*y + 1) + 1, -x/(-x*y + 1)], [-y/(-x*y + 1), 1/(-x*y + 1)]])

MINV
⎡  x⋅y           -x    ⎤
⎢──────── + 1  ────────⎥
⎢-x⋅y + 1      -x⋅y + 1⎥
⎢                      ⎥
⎢    -y           1    ⎥
⎢  ────────    ────────⎥
⎣  -x⋅y + 1    -x⋅y + 1⎦

------------------------
M.det = -x*y + 1
