# Python "científico": módulos `numpy` e `sympy`

![](images_scipython/sci_python.png)

## `numpy`

### Operações "vectoriais"

In [1]:
import numpy as np

# outras possibilidades:

# import numpy
# from numpy import *
# from numpy import linspace array arange

In [2]:
x = np.linspace (0.0, 2.5, 20)
print 'x'
print x

y = 4 * x**2 -3

print 
print 'y'
print y

x
[ 0.          0.13157895  0.26315789  0.39473684  0.52631579  0.65789474
  0.78947368  0.92105263  1.05263158  1.18421053  1.31578947  1.44736842
  1.57894737  1.71052632  1.84210526  1.97368421  2.10526316  2.23684211
  2.36842105  2.5       ]

y
[ -3.          -2.93074792  -2.72299169  -2.3767313   -1.89196676
  -1.26869806  -0.50692521   0.3933518    1.43213296   2.60941828
   3.92520776   5.37950139   6.97229917   8.70360111  10.5734072
  12.58171745  14.72853186  17.01385042  19.43767313  22.        ]


### Criação de _arrays_

In [3]:
x = np.linspace(1, 2, 10)
print x
print

x = np.arange(1.5, 2.5, 0.1)
print x
print

x = np.array([1, 1.2, 3, 3.5])
print x

[ 1.          1.11111111  1.22222222  1.33333333  1.44444444  1.55555556
  1.66666667  1.77777778  1.88888889  2.        ]

[ 1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4]

[ 1.   1.2  3.   3.5]


### Dimensões (`shape`)

In [4]:
x = np.linspace(1,20,20)
print x
print

x.shape = (5,4)
print x
print

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.  19.  20.]

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [ 13.  14.  15.  16.]
 [ 17.  18.  19.  20.]]



In [5]:
x = np.array([[1, 1.2, 3],[1.3,5.1,1.3]])
print x
print

x = np.ones((3,2))
print x
print

x = np.zeros((3,2))
print x
print

x = np.eye(3)
print x
print

x = np.diag([1.2, 3.2, 4.1, 6.3])
print x
print

[[ 1.   1.2  3. ]
 [ 1.3  5.1  1.3]]

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

[[ 1.2  0.   0.   0. ]
 [ 0.   3.2  0.   0. ]
 [ 0.   0.   4.1  0. ]
 [ 0.   0.   0.   6.3]]



### Indexação a várias dimensões

In [14]:
x = np.linspace(1,20,20).reshape((5,4))
print x
print
print x[3,1]
print
print x[3, :]
print
print x[0:2, 0:2]

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [ 13.  14.  15.  16.]
 [ 17.  18.  19.  20.]]

14.0

[ 13.  14.  15.  16.]

[[ 1.  2.]
 [ 5.  6.]]


### Indexação booleana

In [17]:
x = np.linspace(1,20,20)
print x > 7
print
print x[x > 7]

[False False False False False False False  True  True  True  True  True
  True  True  True  True  True  True  True  True]

[  8.   9.  10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]


### Indexação com listas de inteiros ou _arrays_

In [24]:
x = np.linspace(5,15,11)
print x
print

i = [1,4,5,6,8]
print x[i]

[  5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.]

[  6.   9.  10.  11.  13.]


### Exemplos de funções do módulo

In [6]:
x = np.roots ([1.0,2.0,1.0,1.0])
print
print 'raízes de x**3 + 2 x**2 + x + 1'
print x
print '\nvalores aleatórios da distribuição de Poisson'
print np.random.poisson(3, 20)
print '\nvalores aleatórios da distribuição N(0,1)'
print np.random.randn(5)


raízes de x**3 + 2 x**2 + x + 1
[-1.75487767+0.j         -0.12256117+0.74486177j -0.12256117-0.74486177j]

valores aleatórios da distribuição de poisson
[5 4 0 4 2 6 3 2 2 3 4 3 5 3 6 0 5 6 5 1]

valores aleatórios da distribuição N(0,1)
[-0.52529147  0.31741362  0.20705439 -1.28181828 -0.82659279]


### Matrizes e álgebra linear

In [37]:
A = np.matrix ([[1, 2, 3], [2, 1, 6], [1, 7, 4]])

print 'A'
print A
print

B = np.matrix ([1,2,3])
print 'B'
print B
print

BT = B.T 
print 'B.T'
print BT
print

C = A * B.T
print 'C = A * B.T'
print C

A
[[1 2 3]
 [2 1 6]
 [1 7 4]]

B
[[1 2 3]]

B.T
[[1]
 [2]
 [3]]

C = A * B.T
[[14]
 [22]
 [27]]


In [36]:
A = np.matrix ([[1.0, 2, 3], [2, 1, 6], [1, 7, 4]])
print 'A'
print A
print

B = np.matrix ([1,2,3]).T
print 'B'
print B
print

X = np.linalg.solve(A, B)
print 'X (solução de A*X = B)'
print X

A
[[ 1.  2.  3.]
 [ 2.  1.  6.]
 [ 1.  7.  4.]]

B
[[1]
 [2]
 [3]]

X (solução de A*X = B)
[[-5.]
 [ 0.]
 [ 2.]]


In [40]:
A = np.matrix ([[1.0, 2, 3], [2, 1, 6], [1, 7, 4]])
print 'A'
print A
print

AINV = np.linalg.inv(A)
print 'A**-1'
print AINV
print

X = A * AINV
print 'A * A**-1'
print X
print

d = np.linalg.det(A)
print 'det(A) = ', d

A
[[ 1.  2.  3.]
 [ 2.  1.  6.]
 [ 1.  7.  4.]]

A**-1
[[ 12.66666667  -4.33333333  -3.        ]
 [  0.66666667  -0.33333333   0.        ]
 [ -4.33333333   1.66666667   1.        ]]

A * A**-1
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

det(A) =  -3.0


### Exemplos de operações vectoriais

In [2]:
#somar os primeiros 20 quadrados perfeitos
print sum(np.arange(20)**2)

2470


In [3]:
## #somar as raízes quadradas que são numeros inteiros at 100
roots = np.arange(0,101)**0.5
print sum(roots[np.trunc(roots) == roots])

55.0


In [4]:
#mostrar que as diferenças entre os quadrados perfeitos sucessivos são os numeros ímpares
quads = np.arange(20)**2
difs = quads[1:] - quads[0:-1]
print difs

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [6]:
# mostrar que a série alternada dos inversos converge para log 2
i = np.arange(1,1000000)
difs =  np.add.accumulate((-1)**(i+1) * 1.0/i) - np.log(2)
print difs[-20:]

[ -5.00009693e-07   5.00009307e-07  -5.00008693e-07   5.00008307e-07
  -5.00007693e-07   5.00007307e-07  -5.00006693e-07   5.00006307e-07
  -5.00005693e-07   5.00005307e-07  -5.00004693e-07   5.00004307e-07
  -5.00003693e-07   5.00003307e-07  -5.00002693e-07   5.00002307e-07
  -5.00001693e-07   5.00001307e-07  -5.00000693e-07   5.00000307e-07]


## `sympy`

### Símbolos e álgebra básica

In [1]:
from sympy import Symbol

x = Symbol('x')
y = Symbol('y')

expr = 2**x + x**2 -3

print expr
print
print x+y+x-y

2**x + x**2 - 3

2*x


In [2]:
a = (x+y)**2
print a
print a.expand()
print
print a.subs(x, 1).expand()
print a.subs(x, 1).expand().subs(y, 1)

(x + y)**2
x**2 + 2*x*y + y**2

y**2 + 2*y + 1
4


### Limites

In [5]:
from sympy import Symbol, limit, diff, integrate, sin, oo

x = Symbol('x')
y = Symbol('y')

expr = 2**x + x**2 -3

print expr

print limit(sin(x)/x, x, 0)
print limit(x, x, oo)
print limit(1/x, x, oo)

2**x + x**2 - 3
1
oo
0


### Derivadas e integrais

In [6]:
print diff(sin(x), x)
print diff(sin(2*x), x)
print diff(expr, x)
print diff(expr, x, 3)
print '-------------------------------'
print integrate(sin(x), x)

cos(x)
2*cos(2*x)
2**x*log(2) + 2*x
2**x*log(2)**3
-------------------------------
-cos(x)


In [53]:
from sympy import Symbol, Matrix, pprint

x = Symbol('x')
y = Symbol('y')

M = Matrix([[1,x], [y,1]])
print 'M'
print M
print
print 'M'
pprint(M)
print '\n------------------------'

MINV = M.inv()
print 'MINV'
print MINV
print
print 'MINV'
pprint(MINV)

print '\n------------------------'
d = M.det()
print 'M.det =', d

M
Matrix([[1, x], [y, 1]])

M
⎡1  x⎤
⎢    ⎥
⎣y  1⎦

------------------------
MINV
Matrix([[x*y/(-x*y + 1) + 1, -x/(-x*y + 1)], [-y/(-x*y + 1), 1/(-x*y + 1)]])

MINV
⎡  x⋅y           -x    ⎤
⎢──────── + 1  ────────⎥
⎢-x⋅y + 1      -x⋅y + 1⎥
⎢                      ⎥
⎢    -y           1    ⎥
⎢  ────────    ────────⎥
⎣  -x⋅y + 1    -x⋅y + 1⎦

------------------------
M.det = -x*y + 1
